name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Hello World
      run: echo 'Hello World'
    
    - name: Build C# 
      run: dotnet build

    - name: Test C# 
      run: dotnet test

    - name: typescript
      working-directory: DotnetTemplate.Web
      run: |
        npm install
        npm run build
        npm run lint
        npm t
